### ISSUE TITLE
IsCreditCardNumberValid is invalid

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#1]
Your IsCreditCardNumberValid method expects 16 digits only and crashes every time I pass some values like these ones:
"5555 5555 5555 4444"
"35301113333000001"
"3530 1113 3330 0000"
etc.

**Comment by tiamalist** [comment]
Всі три issues основані на одному і тому ж Exseption так всі три функції використовуються в одній головній функції "Main()", причина даного Exseption переповнення у функції IsCreditCardNumberValid при обявленні масиву 
![mas](https://cloud.githubusercontent.com/assets/10754962/15093143/02bf371a-1487-11e6-9997-166344bfaab8.jpg)
. 
Виправлення даного Exseption, збільшення розміру масиву до 23 символів, із інформації яка була надана у завданні №1: 
![info](https://cloud.githubusercontent.com/assets/10754962/15093159/6ab01bbe-1487-11e6-8fe3-68b2f798cb4b.jpg) , максимальний розмір карти який може бути 19 символів
плюс символ пробілу (або будь який інший) який групує номер по чотири символа, і того 23 символа.
