### ISSUE TITLE
GetCreditCardVendor is invalid

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#2]
Try the following card numbers (your method doesn't return expected vendors):
"3566 0020 2036 0505" (JCB)
"5000000000000611" (Maestro)
"371449635398431" (American Express)

**Comment by tiamalist** [comment]
В мене при вводі вище вказаних номерів повертаються відповідний вендор.
"3566 0020 2036 0505" (JCB) - якщо його вводити у відповідному форматі то  результат буде "есепшин" через причину переповнення у функції  IsCreditCardNumberValid параметр розміру масиву, так як я вказував його в розмірі 16, а при використанні вище вказаного методу вводу символів 20, а в моєму коді не планувалось використовувати  ">16" символів, 
![exception_1](https://cloud.githubusercontent.com/assets/10754962/15093011/1b33c5d0-1483-11e6-93b2-44ffe862d6a5.jpg), але визначення вендора проходить успішно.
Це ж стосується і наступних прикладів: 
"5000000000000611" (Maestro) 
![maestro](https://cloud.githubusercontent.com/assets/10754962/15093037/c9c5d5c0-1483-11e6-80f2-a471ceafbeff.jpg) 
"371449635398431" (American Express)  
![american express](https://cloud.githubusercontent.com/assets/10754962/15093046/0ff7ab90-1484-11e6-83be-6e54e38f6fd8.jpg)
