### ISSUE TITLE
IsCreditCardNumberValid doesn't return true for valid card numbers

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#4]
[Image ](http://s32.postimg.org/smhrkkf2t/24214.png)contains valid numbers.

**Comment by kakarotto67** [comment]
Also, "35301113333000001" is not valid, but IsCreditCardNumberValid returns true.

**Comment by tiamalist** [comment]
Добавлено перевірку на відповідність кількості символів до вендора
