### ISSUE TITLE
GetCreditCardVendor doesn't return valid vendor for valid numbers

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#5]
[Image ](http://s32.postimg.org/vmvusuwr9/24142421421.png) contains valid numbers and vendors (check method name and its input parameter).

**Comment by tiamalist** [comment]
Як не передавати номер (з групуванням чи без), назва вендора повертається правильно.
![gccv](https://cloud.githubusercontent.com/assets/10754962/15151825/902bd2e2-16db-11e6-96e5-d067ca8c6c90.jpg)
![gccv-2](https://cloud.githubusercontent.com/assets/10754962/15151912/f0c69984-16db-11e6-8931-66f8c6145609.jpg)
