### ISSUE TITLE
GenerateNextCreditCardNumber generates incorrect card number

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#6]
Pass "4999999999999999993" (VISA)
Expected: no more valid numbers left for visa
Actual: "5000000000000000005", but this is not visa

**Comment by tiamalist** [comment]
Добавлена перевірка 
![gncn](https://cloud.githubusercontent.com/assets/10754962/15159331/e1b6ec52-16fc-11e6-8af7-a5c3d2c57c39.jpg)
