### ISSUE TITLE
Your code isn't merged well

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCart#7]
Check your Program.cs file. It contains such constructions:
<<<<<<< HEAD, ======= , etc.
It means that your code isn't merged well, so I can't check it.

**Comment by tiamalist** [comment]
Я вчора ввечері писав на електронну пошту:
"Привіт

При завантаженні оновленого коду на github посипались помилки, і більшість коду не дієздатна, тому я створив новий репозиторій куди завантажив оновлений код із внесеними змінами (виправленими Issues), на які Роман сьогодні вказував.

https://github.com/tiamalist/myCreditCard"
